// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktqrukvljxsebcrqvbdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0cXJ1a3ZsanhzZWJjcnF2YmRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1Nzk4NDcsImV4cCI6MjA3MTE1NTg0N30.BAJg6oEPE5YJvsZUTEtoy6ClXjxuE-fCUsQ-wOHH-Pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});