name: Supabase Keep-Alive

on:
  # schedule:
  #   # Run every 6 hours to keep the database alive
  #   - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual trigger only

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          echo "🔄 Pinging Supabase database to keep it alive..."
          curl -X POST "https://ktqrukvljxsebcrqvbdp.supabase.co/functions/v1/keep-alive" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            --fail-with-body
          
          echo "✅ Database keep-alive ping completed successfully!"
          echo "⏰ Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"